--//////////////////////////////////////////////////////
--//////////////////////////////////////////////////////
-- === 1. BẢNG NUOC (Mã nhập tay VARCHAR) ===
CREATE PROCEDURE Nuoc_GetAll AS
BEGIN SELECT * FROM Nuoc ORDER BY TenNuoc END
GO
CREATE PROCEDURE Nuoc_GetById @MaNuoc VARCHAR(20) AS
BEGIN SELECT * FROM Nuoc WHERE MaNuoc = @MaNuoc END
GO
CREATE PROCEDURE Nuoc_Insert @MaNuoc VARCHAR(20), @TenNuoc NVARCHAR(100) AS
BEGIN
    -- Kiểm tra trùng mã trước khi thêm
    IF NOT EXISTS (SELECT 1 FROM Nuoc WHERE MaNuoc = @MaNuoc)
        INSERT INTO Nuoc VALUES (@MaNuoc, @TenNuoc)
END
GO
CREATE OR ALTER PROCEDURE Nuoc_Update
    @MaNuocCu nvarchar(20),  -- Tham số mới thêm vào
    @MaNuocMoi nvarchar(20), -- Mã người dùng nhập trên form
    @TenNuoc nvarchar(100)
AS
BEGIN
    UPDATE Nuoc
    SET 
        MaNuoc = @MaNuocMoi,
        TenNuoc = @TenNuoc
    WHERE MaNuoc = @MaNuocCu -- Tìm theo mã cũ
END
GO
CREATE PROCEDURE Nuoc_Delete @MaNuoc VARCHAR(20) AS
BEGIN DELETE FROM Nuoc WHERE MaNuoc=@MaNuoc END
GO

-- === 2. BẢNG TINH (Mã nhập tay INT) ===
CREATE PROCEDURE Tinh_GetAll AS
BEGIN SELECT * FROM Tinh ORDER BY MaTinh END
GO
CREATE PROCEDURE Tinh_GetById @MaTinh INT AS
BEGIN SELECT * FROM Tinh WHERE MaTinh = @MaTinh END
GO
CREATE PROCEDURE Tinh_Insert @MaTinh INT, @TenTinh NVARCHAR(20) AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM Tinh WHERE MaTinh = @MaTinh)
        INSERT INTO Tinh VALUES (@MaTinh, @TenTinh)
END
GO
CREATE PROCEDURE Tinh_Update
    @MaTinhCu int,  -- THAM SỐ 1: Dùng để tìm (WHERE)
    @MaTinhMoi int, -- THAM SỐ 2: Dùng để lưu (SET)
    @TenTinh nvarchar(20)   -- THAM SỐ 3: Dùng để lưu (SET)
AS
BEGIN
    UPDATE Tinh
    SET 
        MaTinh = @MaTinhMoi,  -- Cột MaTinh lấy giá trị từ tham số @MaTinhMoi
        TenTinh = @TenTinh    -- Cột TenTinh lấy giá trị từ tham số @TenTinh
    WHERE 
        MaTinh = @MaTinhCu    -- Tìm dòng có MaTinh khớp với @MaTinhCu
END
CREATE PROCEDURE Tinh_Delete @MaTinh INT AS
BEGIN DELETE FROM Tinh WHERE MaTinh=@MaTinh END
GO
-- === 3. BẢNG DONVITINH ===
CREATE PROCEDURE DonViTinh_GetAll AS BEGIN SELECT * FROM DonViTinh ORDER BY MaDVT END
GO
CREATE PROCEDURE DonViTinh_GetById @MaDVT INT AS BEGIN SELECT * FROM DonViTinh WHERE MaDVT = @MaDVT END
GO
CREATE PROCEDURE DonViTinh_Insert @TenDVT NVARCHAR(50) AS
BEGIN
    DECLARE @MaDVT INT = 1
    WHILE (@MaDVT IN (SELECT MaDVT FROM DonViTinh)) SET @MaDVT += 1
    INSERT INTO DonViTinh VALUES (@MaDVT, @TenDVT)
END
GO
CREATE PROCEDURE DonViTinh_Update @MaDVT INT, @TenDVT NVARCHAR(50) AS
BEGIN UPDATE DonViTinh SET TenDVT=@TenDVT WHERE MaDVT=@MaDVT END
GO
CREATE PROCEDURE DonViTinh_Delete @MaDVT INT AS BEGIN DELETE FROM DonViTinh WHERE MaDVT=@MaDVT END
GO

-- === 4. BẢNG NHOMSP ===
CREATE PROCEDURE NhomSP_GetAll
AS
BEGIN
    SELECT * FROM NhomSP ORDER BY MaNhomSP
END
GO

CREATE PROCEDURE NhomSP_GetById @MaNhomSP INT
AS
BEGIN
    SELECT * FROM NhomSP WHERE MaNhomSP = @MaNhomSP
END
GO

CREATE PROCEDURE NhomSP_Insert @TenNhomSP NVARCHAR(100)
AS
BEGIN
    DECLARE @MaNhomSP INT = 1
    WHILE (@MaNhomSP IN (SELECT MaNhomSP FROM NhomSP)) SET @MaNhomSP += 1
    INSERT INTO NhomSP VALUES (@MaNhomSP, @TenNhomSP)
END
GO

CREATE PROCEDURE NhomSP_Update @MaNhomSP INT, @TenNhomSP NVARCHAR(100)
AS
BEGIN
    UPDATE NhomSP SET TenNhomSP=@TenNhomSP WHERE MaNhomSP=@MaNhomSP
END
GO

CREATE PROCEDURE NhomSP_Delete @MaNhomSP INT
AS
BEGIN
    DELETE FROM NhomSP WHERE MaNhomSP=@MaNhomSP
END
GO

-- === 5. BẢNG LOAISP ===
CREATE PROCEDURE LoaiSP_GetAll AS BEGIN SELECT * FROM LoaiSP ORDER BY MaLSP END
GO
CREATE PROCEDURE LoaiSP_GetById @MaLSP INT AS BEGIN SELECT * FROM LoaiSP WHERE MaLSP = @MaLSP END
GO
CREATE PROCEDURE LoaiSP_Insert @TenLSP NVARCHAR(100), @MaNhomSP INT AS
BEGIN
    DECLARE @MaLSP INT = 1
    WHILE (@MaLSP IN (SELECT MaLSP FROM LoaiSP)) SET @MaLSP += 1
    INSERT INTO LoaiSP VALUES (@MaLSP, @TenLSP, @MaNhomSP)
END
GO
CREATE PROCEDURE LoaiSP_Update @MaLSP INT, @TenLSP NVARCHAR(100), @MaNhomSP INT AS
BEGIN UPDATE LoaiSP SET TenLSP=@TenLSP, MaNhomSP=@MaNhomSP WHERE MaLSP=@MaLSP END
GO
CREATE PROCEDURE LoaiSP_Delete @MaLSP INT AS BEGIN DELETE FROM LoaiSP WHERE MaLSP=@MaLSP END
GO

-- === 6. BẢNG HANGSX ===
CREATE PROCEDURE HangSX_GetAll AS BEGIN SELECT * FROM HangSX ORDER BY MaHSX END
GO
CREATE PROCEDURE HangSX_GetById @MaHSX INT AS BEGIN SELECT * FROM HangSX WHERE MaHSX = @MaHSX END
GO
CREATE PROCEDURE HangSX_Insert @TenHSX NVARCHAR(255), @MaNuoc VARCHAR(20) AS
BEGIN
    DECLARE @MaHSX INT = 1
    WHILE (@MaHSX IN (SELECT MaHSX FROM HangSX)) SET @MaHSX += 1
    INSERT INTO HangSX VALUES (@MaHSX, @TenHSX, @MaNuoc)
END
GO
CREATE PROCEDURE HangSX_Update @MaHSX INT, @TenHSX NVARCHAR(255), @MaNuoc VARCHAR(20) AS
BEGIN UPDATE HangSX SET TenHSX=@TenHSX, MaNuoc=@MaNuoc WHERE MaHSX=@MaHSX END
GO
CREATE PROCEDURE HangSX_Delete @MaHSX INT AS BEGIN DELETE FROM HangSX WHERE MaHSX=@MaHSX END
GO

-- === 7. BẢNG LOAINV ===
CREATE PROCEDURE LoaiNV_GetAll AS BEGIN SELECT * FROM LoaiNV ORDER BY MaLNV END
GO
CREATE PROCEDURE LoaiNV_GetById @MaLNV INT AS BEGIN SELECT * FROM LoaiNV WHERE MaLNV = @MaLNV END
GO
CREATE PROCEDURE LoaiNV_Insert @TenLNV NVARCHAR(100) AS
BEGIN
    DECLARE @MaLNV INT = 1
    WHILE (@MaLNV IN (SELECT MaLNV FROM LoaiNV)) SET @MaLNV += 1
    INSERT INTO LoaiNV VALUES (@MaLNV, @TenLNV)
END
GO
CREATE PROCEDURE LoaiNV_Update @MaLNV INT, @TenLNV NVARCHAR(100) AS
BEGIN UPDATE LoaiNV SET TenLNV=@TenLNV WHERE MaLNV=@MaLNV END
GO
CREATE PROCEDURE LoaiNV_Delete @MaLNV INT AS BEGIN DELETE FROM LoaiNV WHERE MaLNV=@MaLNV END
GO

-- === 8. BẢNG XA ===
CREATE PROCEDURE Xa_GetAll AS BEGIN SELECT * FROM Xa ORDER BY MaXa END
GO
CREATE PROCEDURE Xa_GetById @MaXa INT AS BEGIN SELECT * FROM Xa WHERE MaXa = @MaXa END
GO
CREATE PROCEDURE Xa_Insert @TenXa NVARCHAR(50), @MaTinh INT AS
BEGIN
    DECLARE @MaXa INT = 1
    WHILE (@MaXa IN (SELECT MaXa FROM Xa)) SET @MaXa += 1
    INSERT INTO Xa VALUES (@MaXa, @TenXa, @MaTinh)
END
GO
CREATE PROCEDURE Xa_Update @MaXa INT, @TenXa NVARCHAR(50), @MaTinh INT AS
BEGIN UPDATE Xa SET TenXa=@TenXa, MaTinh=@MaTinh WHERE MaXa=@MaXa END
GO
CREATE PROCEDURE Xa_Delete @MaXa INT AS BEGIN DELETE FROM Xa WHERE MaXa=@MaXa END
GO

-- === 9. BẢNG TRẠNG THÁI ===
CREATE PROCEDURE TrangThai_GetAll AS BEGIN SELECT * FROM TrangThai ORDER BY MaTT END
GO
CREATE PROCEDURE TrangThai_GetById @MaTT INT AS BEGIN SELECT * FROM TrangThai WHERE MaTT = @MaTT END
GO
CREATE PROCEDURE TrangThai_Insert @TenTT NVARCHAR(50) AS
BEGIN
    DECLARE @MaTT INT = 1
    WHILE (@MaTT IN (SELECT MaTT FROM TrangThai)) SET @MaTT += 1
    INSERT INTO TrangThai VALUES (@MaTT, @TenTT)
END
GO
CREATE PROCEDURE TrangThai_Update @MaTT INT, @TenTT NVARCHAR(50) AS
BEGIN UPDATE TrangThai SET TenTT=@TenTT WHERE MaTT=@MaTT END
GO
CREATE PROCEDURE TrangThai_Delete @MaTT INT AS BEGIN DELETE FROM TrangThai WHERE MaTT=@MaTT END
GO
-- === 10. BẢNG TRANGTHAIDBH (Trạng thái Đơn Bán Hàng) ===
CREATE PROCEDURE TrangThaiDBH_GetAll 
AS 
BEGIN 
    SELECT * FROM TrangThaiDBH ORDER BY MaTTDBH 
END
GO

CREATE PROCEDURE TrangThaiDBH_GetById @MaTTDBH INT 
AS 
BEGIN 
    SELECT * FROM TrangThaiDBH WHERE MaTTDBH = @MaTTDBH 
END
GO

CREATE PROCEDURE TrangThaiDBH_Insert @TenTTDBH NVARCHAR(50) 
AS
BEGIN
    DECLARE @MaTTDBH INT = 1
    -- Tìm mã số nguyên nhỏ nhất chưa được sử dụng
    WHILE (@MaTTDBH IN (SELECT MaTTDBH FROM TrangThaiDBH)) 
    BEGIN
        SET @MaTTDBH += 1
    END
    
    INSERT INTO TrangThaiDBH(MaTTDBH, TenTTDBH) VALUES (@MaTTDBH, @TenTTDBH)
END
GO

CREATE PROCEDURE TrangThaiDBH_Update @MaTTDBH INT, @TenTTDBH NVARCHAR(50) 
AS
BEGIN 
    UPDATE TrangThaiDBH SET TenTTDBH=@TenTTDBH WHERE MaTTDBH=@MaTTDBH 
END
GO

CREATE PROCEDURE TrangThaiDBH_Delete @MaTTDBH INT 
AS 
BEGIN 
    DELETE FROM TrangThaiDBH WHERE MaTTDBH=@MaTTDBH 
END
GO

-- === 11. BẢNG TRANGTHAIDMH (Trạng thái Đơn Mua Hàng) ===
CREATE PROCEDURE TrangThaiDMH_GetAll 
AS 
BEGIN 
    SELECT * FROM TrangThaiDMH ORDER BY MaTTDMH 
END
GO

CREATE PROCEDURE TrangThaiDMH_GetById @MaTTDMH INT 
AS 
BEGIN 
    SELECT * FROM TrangThaiDMH WHERE MaTTDMH = @MaTTDMH 
END
GO

CREATE PROCEDURE TrangThaiDMH_Insert @TenTTDMH NVARCHAR(50) 
AS
BEGIN
    DECLARE @MaTTDMH INT = 1
    -- Tìm mã số nguyên nhỏ nhất chưa được sử dụng
    WHILE (@MaTTDMH IN (SELECT MaTTDMH FROM TrangThaiDMH)) 
    BEGIN
        SET @MaTTDMH += 1
    END
    
    INSERT INTO TrangThaiDMH(MaTTDMH, TenTTDMH) VALUES (@MaTTDMH, @TenTTDMH)
END
GO

CREATE PROCEDURE TrangThaiDMH_Update @MaTTDMH INT, @TenTTDMH NVARCHAR(50) 
AS
BEGIN 
    UPDATE TrangThaiDMH SET TenTTDMH=@TenTTDMH WHERE MaTTDMH=@MaTTDMH 
END
GO

CREATE PROCEDURE TrangThaiDMH_Delete @MaTTDMH INT 
AS 
BEGIN 
    DELETE FROM TrangThaiDMH WHERE MaTTDMH=@MaTTDMH 
END
GO

-- === 12. BẢNG NHANVIEN ===
CREATE PROCEDURE NhanVien_GetAll AS BEGIN SELECT * FROM NhanVien ORDER BY MaNV END
GO
CREATE PROCEDURE NhanVien_GetById @MaNV INT AS BEGIN SELECT * FROM NhanVien WHERE MaNV = @MaNV END
GO
CREATE PROCEDURE NhanVien_Insert 
    @TenDN VARCHAR(50), @MatKhau VARCHAR(100), @HoNV NVARCHAR(50), @TenNV NVARCHAR(50),
    @GioiTinh NVARCHAR(10), @DienThoai VARCHAR(12), @Email VARCHAR(255), 
    @DiaChi NVARCHAR(255), @MaLNV INT, @MaXa INT
AS
BEGIN
    DECLARE @MaNV INT = 1
    WHILE (@MaNV IN (SELECT MaNV FROM NhanVien)) SET @MaNV += 1
    INSERT INTO NhanVien VALUES (@MaNV, @TenDN, @MatKhau, @HoNV, @TenNV, @GioiTinh, @DienThoai, @Email, @DiaChi, @MaLNV, @MaXa)
END
GO
CREATE PROCEDURE NhanVien_Update 
    @MaNV INT, @TenDN VARCHAR(50), @MatKhau VARCHAR(100), @HoNV NVARCHAR(50), @TenNV NVARCHAR(50),
    @GioiTinh NVARCHAR(10), @DienThoai VARCHAR(12), @Email VARCHAR(255), 
    @DiaChi NVARCHAR(255), @MaLNV INT, @MaXa INT
AS
BEGIN
    UPDATE NhanVien SET 
        TenDN=@TenDN, MatKhau=@MatKhau, HoNV=@HoNV, TenNV=@TenNV, GioiTinh=@GioiTinh,
        DienThoai=@DienThoai, Email=@Email, DiaChi=@DiaChi, MaLNV=@MaLNV, MaXa=@MaXa
    WHERE MaNV=@MaNV
END
GO
CREATE PROCEDURE NhanVien_Delete @MaNV INT AS BEGIN DELETE FROM NhanVien WHERE MaNV=@MaNV END
GO

-- === 13. BẢNG KHACHHANG ===
CREATE PROCEDURE KhachHang_GetAll AS BEGIN SELECT * FROM KhachHang ORDER BY MaKH END
GO
CREATE PROCEDURE KhachHang_GetById @MaKH INT AS BEGIN SELECT * FROM KhachHang WHERE MaKH = @MaKH END
GO
CREATE PROCEDURE KhachHang_Insert 
    @TenDN VARCHAR(50), @MatKhau VARCHAR(100), @HoKH NVARCHAR(50), @TenKH NVARCHAR(50),
    @AnhKH VARCHAR(255), @DiaChi NVARCHAR(255), @SDT VARCHAR(12), @MaXa INT
AS
BEGIN
    DECLARE @MaKH INT = 1
    WHILE (@MaKH IN (SELECT MaKH FROM KhachHang)) SET @MaKH += 1
    INSERT INTO KhachHang VALUES (@MaKH, @TenDN, @MatKhau, @HoKH, @TenKH, @AnhKH, @DiaChi, @SDT, @MaXa)
END
GO
CREATE PROCEDURE KhachHang_Update 
    @MaKH INT, @TenDN VARCHAR(50), @MatKhau VARCHAR(100), @HoKH NVARCHAR(50), @TenKH NVARCHAR(50),
    @AnhKH VARCHAR(255), @DiaChi NVARCHAR(255), @SDT VARCHAR(12), @MaXa INT
AS
BEGIN
    UPDATE KhachHang SET 
        TenDN=@TenDN, MatKhau=@MatKhau, HoKH=@HoKH, TenKH=@TenKH, AnhKH=@AnhKH,
        DiaChi=@DiaChi, SDT=@SDT, MaXa=@MaXa
    WHERE MaKH=@MaKH
END
GO
CREATE PROCEDURE KhachHang_Delete @MaKH INT AS BEGIN DELETE FROM KhachHang WHERE MaKH=@MaKH END
GO

-- === 14. BẢNG NHACC ===
CREATE PROCEDURE NhaCC_GetAll AS BEGIN SELECT * FROM NhaCC ORDER BY MaNCC END
GO
CREATE PROCEDURE NhaCC_GetById @MaNCC INT AS BEGIN SELECT * FROM NhaCC WHERE MaNCC = @MaNCC END
GO
CREATE PROCEDURE NhaCC_Insert 
    @TenNCC NVARCHAR(255), @DiaChiNCC NVARCHAR(255), @DienThoaiNCC VARCHAR(12), 
    @EmailNCC VARCHAR(255), @MaXa INT
AS
BEGIN
    DECLARE @MaNCC INT = 1
    WHILE (@MaNCC IN (SELECT MaNCC FROM NhaCC)) SET @MaNCC += 1
    INSERT INTO NhaCC VALUES (@MaNCC, @TenNCC, @DiaChiNCC, @DienThoaiNCC, @EmailNCC, @MaXa)
END
GO
CREATE PROCEDURE NhaCC_Update 
    @MaNCC INT, @TenNCC NVARCHAR(255), @DiaChiNCC NVARCHAR(255), @DienThoaiNCC VARCHAR(12), 
    @EmailNCC VARCHAR(255), @MaXa INT
AS
BEGIN
    UPDATE NhaCC SET 
        TenNCC=@TenNCC, DiaChiNCC=@DiaChiNCC, DienThoaiNCC=@DienThoaiNCC, EmailNCC=@EmailNCC, MaXa=@MaXa
    WHERE MaNCC=@MaNCC
END
GO
CREATE PROCEDURE NhaCC_Delete @MaNCC INT AS BEGIN DELETE FROM NhaCC WHERE MaNCC=@MaNCC END
GO

-- === 15. BẢNG SANPHAM (Trung tâm) ===
CREATE PROCEDURE SanPham_GetAll AS BEGIN SELECT * FROM SanPham ORDER BY MaSP END
GO
CREATE PROCEDURE SanPham_GetById @MaSP INT AS BEGIN SELECT * FROM SanPham WHERE MaSP = @MaSP END
GO
CREATE PROCEDURE SanPham_Insert 
    @TenSP NVARCHAR(100), @Dongia DECIMAL(18,0), @AnhSP VARCHAR(255), @MoTaSP NVARCHAR(255),
    @MaLSP INT, @MaDVT INT, @MaTT INT, @MaHSX INT
AS
BEGIN
    DECLARE @MaSP INT = 1
    WHILE (@MaSP IN (SELECT MaSP FROM SanPham)) SET @MaSP += 1
    INSERT INTO SanPham VALUES (@MaSP, @TenSP, @Dongia, @AnhSP, @MoTaSP, @MaLSP, @MaDVT, @MaTT, @MaHSX)
END
GO
CREATE PROCEDURE SanPham_Update 
    @MaSP INT, @TenSP NVARCHAR(100), @Dongia DECIMAL(18,0), @AnhSP VARCHAR(255), @MoTaSP NVARCHAR(255),
    @MaLSP INT, @MaDVT INT, @MaTT INT, @MaHSX INT
AS
BEGIN
    UPDATE SanPham SET 
        TenSP=@TenSP, Dongia=@Dongia, AnhSP=@AnhSP, MoTaSP=@MoTaSP,
        MaLSP=@MaLSP, MaDVT=@MaDVT, MaTT=@MaTT, MaHSX=@MaHSX
    WHERE MaSP=@MaSP
END
GO
CREATE PROCEDURE SanPham_Delete @MaSP INT AS BEGIN DELETE FROM SanPham WHERE MaSP=@MaSP END
GO

-- === 16. BẢNG DONMUAHANG ===
CREATE PROCEDURE DonMuaHang_GetAll AS BEGIN SELECT * FROM DonMuaHang ORDER BY MaDMH END
GO
CREATE PROCEDURE DonMuaHang_GetById @MaDMH INT AS BEGIN SELECT * FROM DonMuaHang WHERE MaDMH = @MaDMH END
GO
CREATE PROCEDURE DonMuaHang_Insert 
    @NgayMua DATETIME, @MaNCC INT, @MaNV INT, @MaTTDMH INT
AS
BEGIN
    DECLARE @MaDMH INT = 1
    WHILE (@MaDMH IN (SELECT MaDMH FROM DonMuaHang)) SET @MaDMH += 1
    INSERT INTO DonMuaHang VALUES (@MaDMH, @NgayMua, @MaNCC, @MaNV, @MaTTDMH)
END
GO
CREATE PROCEDURE DonMuaHang_Update 
    @MaDMH INT, @NgayMua DATETIME, @MaNCC INT, @MaNV INT, @MaTTDMH INT
AS
BEGIN
    UPDATE DonMuaHang SET NgayMua=@NgayMua, MaNCC=@MaNCC, MaNV=@MaNV, MaTTDMH=@MaTTDMH WHERE MaDMH=@MaDMH
END
GO
CREATE PROCEDURE DonMuaHang_Delete @MaDMH INT AS BEGIN DELETE FROM DonMuaHang WHERE MaDMH=@MaDMH END
GO

-- === 17. BẢNG DONBANHANG ===
CREATE PROCEDURE DonBanHang_GetAll AS BEGIN SELECT * FROM DonBanHang ORDER BY MaDBH END
GO
CREATE PROCEDURE DonBanHang_GetById @MaDBH INT AS BEGIN SELECT * FROM DonBanHang WHERE MaDBH = @MaDBH END
GO
CREATE PROCEDURE DonBanHang_Insert 
    @NgayBan DATETIME, @DiaChiGH NVARCHAR(255), @MaKH INT, @MaXa INT, @MaTTDBH INT
AS
BEGIN
    DECLARE @MaDBH INT = 1
    WHILE (@MaDBH IN (SELECT MaDBH FROM DonBanHang)) SET @MaDBH += 1
    INSERT INTO DonBanHang VALUES (@MaDBH, @NgayBan, @DiaChiGH, @MaKH, @MaXa, @MaTTDBH)
END
GO
CREATE PROCEDURE DonBanHang_Update 
    @MaDBH INT, @NgayBan DATETIME, @DiaChiGH NVARCHAR(255), @MaKH INT, @MaXa INT, @MaTTDBH INT
AS
BEGIN
    UPDATE DonBanHang SET NgayBan=@NgayBan, DiaChiGH=@DiaChiGH, MaKH=@MaKH, MaXa=@MaXa, MaTTDBH=@MaTTDBH WHERE MaDBH=@MaDBH
END
GO
CREATE PROCEDURE DonBanHang_Delete @MaDBH INT AS BEGIN DELETE FROM DonBanHang WHERE MaDBH=@MaDBH END
GO
-- === 18. BẢNG CHI TIẾT Bán HÀNG (CTBH) - KHÓA CHÍNH KÉP ===
-- Lưu ý: Bảng chi tiết không sinh mã tự động mà lấy mã từ Đơn hàng và Sản phẩm
CREATE PROCEDURE CTBH_GetAll AS BEGIN SELECT * FROM CTBH END
GO
CREATE PROCEDURE CTBH_GetById @MaDBH INT, @MaSP INT AS 
BEGIN SELECT * FROM CTBH WHERE MaDBH=@MaDBH AND MaSP=@MaSP END
GO
CREATE PROCEDURE CTBH_Insert @MaDBH INT, @MaSP INT, @SLB INT, @DGB DECIMAL(18,0) AS
BEGIN
    INSERT INTO CTBH VALUES (@MaDBH, @MaSP, @SLB, @DGB)
END
GO
CREATE PROCEDURE CTBH_Update @MaDBH INT, @MaSP INT, @SLB INT, @DGB DECIMAL(18,0) AS
BEGIN
    UPDATE CTBH SET SLB=@SLB, DGB=@DGB WHERE MaDBH=@MaDBH AND MaSP=@MaSP
END
GO
CREATE PROCEDURE CTBH_Delete @MaDBH INT, @MaSP INT AS
BEGIN DELETE FROM CTBH WHERE MaDBH=@MaDBH AND MaSP=@MaSP END
GO
-- === 19. BẢNG CHI TIẾT MUA HÀNG (CTMH) - KHÓA CHÍNH KÉP ===
-- Lưu ý: Bảng chi tiết không sinh mã tự động mà lấy mã từ Đơn mua hàng và Sản phẩm
CREATE PROCEDURE CTMH_GetAll AS BEGIN SELECT * FROM CTMH END
GO
CREATE PROCEDURE CTMH_GetById @MaDMH INT, @MaSP INT AS 
BEGIN SELECT * FROM CTMH WHERE MaDMH=@MaDMH AND MaSP=@MaSP END
GO
CREATE PROCEDURE CTMH_Insert @MaDMH INT, @MaSP INT, @SLM INT, @DGM DECIMAL(18,0) AS
BEGIN
    INSERT INTO CTBH VALUES (@MaDMH, @MaSP, @SLM, @DGM)
END
GO
CREATE PROCEDURE CTMH_Update @MaDMH INT, @MaSP INT, @SLM INT, @DGM DECIMAL(18,0) AS
BEGIN
    UPDATE CTMH SET SLM=@SLM, DGM=@DGM WHERE MaDMH=@MaDMH AND MaSP=@MaSP
END
GO
CREATE PROCEDURE CTMH_Delete @MaDMH INT, @MaSP INT AS
BEGIN DELETE FROM CTMH WHERE MaDMH=@MaDMH AND MaSP=@MaSP END
GO
