--1
CREATE PROCEDURE NhomSP_GetAll
AS
BEGIN
    SELECT * FROM NhomSP ORDER BY MaNhomSP
END
GO

CREATE PROCEDURE NhomSP_GetById @MaNhomSP INT
AS
BEGIN
    SELECT * FROM NhomSP WHERE MaNhomSP = @MaNhomSP
END
GO

CREATE PROCEDURE NhomSP_Insert @TenNhomSP NVARCHAR(100)
AS
BEGIN
    DECLARE @MaNhomSP INT = 1
    WHILE (@MaNhomSP IN (SELECT MaNhomSP FROM NhomSP)) SET @MaNhomSP += 1
    INSERT INTO NhomSP VALUES (@MaNhomSP, @TenNhomSP)
END
GO

CREATE PROCEDURE NhomSP_Update @MaNhomSP INT, @TenNhomSP NVARCHAR(100)
AS
BEGIN
    UPDATE NhomSP SET TenNhomSP=@TenNhomSP WHERE MaNhomSP=@MaNhomSP
END
GO

CREATE PROCEDURE NhomSP_Delete @MaNhomSP INT
AS
BEGIN
    DELETE FROM NhomSP WHERE MaNhomSP=@MaNhomSP
END
GO
--2
CREATE PROCEDURE LoaiSP_GetAll
AS
BEGIN
    SELECT * FROM LoaiSP ORDER BY MaLSP
END
GO

CREATE PROCEDURE LoaiSP_GetById @MaLSP INT
AS
BEGIN
    SELECT * FROM LoaiSP WHERE MaLSP=@MaLSP
END
GO

CREATE PROCEDURE LoaiSP_Insert @TenLSP NVARCHAR(100), @MaNhomSP INT
AS
BEGIN
    DECLARE @MaLSP INT = 1
    WHILE (@MaLSP IN (SELECT MaLSP FROM LoaiSP)) SET @MaLSP += 1
    INSERT INTO LoaiSP VALUES (@MaLSP, @TenLSP, @MaNhomSP)
END
GO

CREATE PROCEDURE LoaiSP_Update @MaLSP INT, @TenLSP NVARCHAR(100), @MaNhomSP INT
AS
BEGIN
    UPDATE LoaiSP SET TenLSP=@TenLSP, MaNhomSP=@MaNhomSP WHERE MaLSP=@MaLSP
END
GO

CREATE PROCEDURE LoaiSP_Delete @MaLSP INT
AS
BEGIN
    DELETE FROM LoaiSP WHERE MaLSP=@MaLSP
END
GO

--3
CREATE PROCEDURE NhaCC_GetAll
AS
BEGIN
    SELECT * FROM NhaCC ORDER BY MaNCC
END
GO

CREATE PROCEDURE NhaCC_GetById @MaNCC INT
AS
BEGIN
    SELECT * FROM NhaCC WHERE MaNCC=@MaNCC
END
GO

CREATE PROCEDURE NhaCC_Insert @TenNCC NVARCHAR(100), @DiaChiNCC NVARCHAR(200), @DienThoaiNCC NVARCHAR(12), @EmailNCC nvarchar(320)
AS
BEGIN
    DECLARE @MaNCC INT = 1
    WHILE (@MaNCC IN (SELECT MaNCC FROM NhaCC)) SET @MaNCC += 1
    INSERT INTO NhaCC VALUES (@MaNCC, @TenNCC, @DiaChiNCC, @DienThoaiNCC, @EmailNCC)
END
GO

CREATE PROCEDURE NhaCC_Update @MaNCC INT, @TenNCC NVARCHAR(100), @DiaChiNCC NVARCHAR(200), @DienThoaiNCC NVARCHAR(12), @EmailNCC nvarchar(320)
AS
BEGIN
    UPDATE NhaCC SET TenNCC=@TenNCC, DiaChiNCC=@DiaChiNCC, DienThoaiNCC=@DienThoaiNCC, EmailNCC=@EmailNCC WHERE MaNCC=@MaNCC
END
GO

CREATE PROCEDURE NhaCC_Delete @MaNCC INT
AS
BEGIN
    DELETE FROM NhaCC WHERE MaNCC=@MaNCC
END
GO

--4
CREATE PROCEDURE Tinh_GetAll
AS
BEGIN
    SELECT * FROM Tinh ORDER BY MaTinh
END
GO

CREATE PROCEDURE Tinh_GetById @MaTinh INT
AS
BEGIN
    SELECT * FROM Tinh WHERE MaTinh=@MaTinh
END
GO

CREATE PROCEDURE Tinh_Insert @TenTinh NVARCHAR(100)
AS
BEGIN
    DECLARE @MaTinh INT = 1
    WHILE (@MaTinh IN (SELECT MaTinh FROM Tinh)) SET @MaTinh += 1
    INSERT INTO Tinh VALUES (@MaTinh, @TenTinh)
END
GO

CREATE PROCEDURE Tinh_Update @MaTinh INT, @TenTinh NVARCHAR(100)
AS
BEGIN
    UPDATE Tinh SET TenTinh=@TenTinh WHERE MaTinh=@MaTinh
END
GO

CREATE PROCEDURE Tinh_Delete @MaTinh INT
AS
BEGIN
    DELETE FROM Tinh WHERE MaTinh=@MaTinh
END
GO

--5
CREATE PROCEDURE Xa_GetAll
AS
BEGIN
    SELECT * FROM Xa ORDER BY MaXa
END
GO

CREATE PROCEDURE Xa_GetById @MaXa INT
AS
BEGIN
    SELECT * FROM Xa WHERE MaXa=@MaXa
END
GO

CREATE PROCEDURE Xa_Insert @TenXa NVARCHAR(100), @MaTinh INT
AS
BEGIN
    DECLARE @MaXa INT = 1
    WHILE (@MaXa IN (SELECT MaXa FROM Xa)) SET @MaXa += 1
    INSERT INTO Xa VALUES (@MaXa, @TenXa, @MaTinh)
END
GO

CREATE PROCEDURE Xa_Update @MaXa INT, @TenXa NVARCHAR(100), @MaTinh INT
AS
BEGIN
    UPDATE Xa SET TenXa=@TenXa, MaTinh=@MaTinh WHERE MaXa=@MaXa
END
GO

CREATE PROCEDURE Xa_Delete @MaXa INT
AS
BEGIN
    DELETE FROM Xa WHERE MaXa=@MaXa
END
GO

--6
CREATE PROCEDURE KhachHang_GetAll
	@Search NVARCHAR(255) = NULL
AS
BEGIN
    SELECT MaKH, TenKH, AnhKH, DiaChi, SDT, MaXa
	FROM KhachHang 
	WHERE @Search IS Null or TenKH LIKE '%' + @Search + '%'
	ORDER BY MaKH
END
GO

--CREATE PROCEDURE KhachHang_GetAll
--AS
--BEGIN
--    SELECT * FROM KhachHang ORDER BY MaKH
--END
--GO


CREATE PROCEDURE KhachHang_GetById @MaKH INT
AS
BEGIN
    SELECT * FROM KhachHang WHERE MaKH=@MaKH
END
GO

CREATE PROCEDURE KhachHang_Insert 
	@TenKH NVARCHAR(100), 
	@AnhKH NVARCHAR(255),
	@DiaChi NVARCHAR(200), 
	@SDT NVARCHAR(20), 
	@MaXa INT
AS
BEGIN
    DECLARE @MaKH INT = 1
    WHILE (@MaKH IN (SELECT MaKH FROM KhachHang)) SET @MaKH += 1
    INSERT INTO KhachHang VALUES (@MaKH, @TenKH, @AnhKH, @DiaChi, @SDT, @MaXa)
END
GO

CREATE PROCEDURE KhachHang_Update 
	@MaKH INT, 
	@TenKH NVARCHAR(100), 
	@AnhKH NVARCHAR(255),
	@DiaChi NVARCHAR(200), 
	@SDT NVARCHAR(20), 
	@MaXa INT
AS
BEGIN
    UPDATE KhachHang SET TenKH=@TenKH, MaKH=@MaKH, DiaChi=@DiaChi, SDT=@SDT, MaXa=@MaXa WHERE MaKH=@MaKH
END
GO

CREATE PROCEDURE KhachHang_Delete @MaKH INT
AS
BEGIN
    DELETE FROM KhachHang WHERE MaKH=@MaKH
END
GO

--7
CREATE PROCEDURE GianHang_GetAll
AS
BEGIN
    SELECT * FROM GianHang ORDER BY MaGH
END
GO

CREATE PROCEDURE GianHang_GetById @MaGH INT
AS
BEGIN
    SELECT * FROM GianHang WHERE MaGH=@MaGH
END
GO

CREATE PROCEDURE GianHang_Insert @TenGH NVARCHAR(100), @MaXa INT
AS
BEGIN
    DECLARE @MaGH INT = 1
    WHILE (@MaGH IN (SELECT MaGH FROM GianHang)) SET @MaGH += 1
    INSERT INTO GianHang VALUES (@MaGH, @TenGH, @MaXa)
END
GO

CREATE PROCEDURE GianHang_Update @MaGH INT, @TenGH NVARCHAR(100), @MaXa INT
AS
BEGIN
    UPDATE GianHang SET TenGH=@TenGH, MaXa=@MaXa WHERE MaGH=@MaGH
END
GO

CREATE PROCEDURE GianHang_Delete @MaGH INT
AS
BEGIN
    DELETE FROM GianHang WHERE MaGH=@MaGH
END
GO

--8
CREATE PROCEDURE DonMuaHang_GetAll
AS
BEGIN
    SELECT * FROM DonMuaHang ORDER BY MaDMH
END
GO

CREATE PROCEDURE DonMuaHang_GetById @MaDMH INT
AS
BEGIN
    SELECT * FROM DonMuaHang WHERE MaDMH=@MaDMH
END
GO

CREATE PROCEDURE DonMuaHang_Insert @NgayMua DATE, @MaNCC INT
AS
BEGIN
    DECLARE @MaDMH INT = 1
    WHILE (@MaDMH IN (SELECT MaDMH FROM DonMuaHang)) SET @MaDMH += 1
    INSERT INTO DonMuaHang VALUES (@MaDMH, @NgayMua, @MaNCC)
END
GO

CREATE PROCEDURE DonMuaHang_Update @MaDMH INT, @NgayMua DATE, @MaNCC INT
AS
BEGIN
    UPDATE DonMuaHang SET NgayMua=@NgayMua, MaNCC=@MaNCC WHERE MaDMH=@MaDMH
END
GO

CREATE PROCEDURE DonMuaHang_Delete @MaDMH INT
AS
BEGIN
    DELETE FROM DonMuaHang WHERE MaDMH=@MaDMH
END
GO

--9
CREATE PROCEDURE DonBanHang_GetAll
AS
BEGIN
    SELECT * FROM DonBanHang ORDER BY MaDBH
END
GO

CREATE PROCEDURE DonBanHang_GetById @MaDBH INT
AS
BEGIN
    SELECT * FROM DonBanHang WHERE MaDBH=@MaDBH
END
GO

CREATE PROCEDURE DonBanHang_Insert @NgayBan DATE, @MaKH INT
AS
BEGIN
    DECLARE @MaDBH INT = 1
    WHILE (@MaDBH IN (SELECT MaDBH FROM DonBanHang)) SET @MaDBH += 1
    INSERT INTO DonBanHang VALUES (@MaDBH, @NgayBan, @MaKH)
END
GO

CREATE PROCEDURE DonBanHang_Update @MaDBH INT, @NgayBan DATE, @MaKH INT
AS
BEGIN
    UPDATE DonBanHang SET NgayBan=@NgayBan, MaKH=@MaKH WHERE MaDBH=@MaDBH
END
GO

CREATE PROCEDURE DonBanHang_Delete @MaDBH INT
AS
BEGIN
    DELETE FROM DonBanHang WHERE MaDBH=@MaDBH
END
GO

--10
CREATE PROCEDURE CTMH_GetAll
AS
BEGIN
    SELECT * FROM CTMH
END
GO

CREATE PROCEDURE CTMH_GetById @MaDMH INT, @MaSP INT
AS
BEGIN
    SELECT * FROM CTMH WHERE MaDMH=@MaDMH AND MaSP=@MaSP
END
GO

CREATE PROCEDURE CTMH_Insert @MaDMH INT, @MaSP INT, @SoLuong INT, @DonGia DECIMAL(18,2)
AS
BEGIN
    INSERT INTO CTMH VALUES (@MaDMH, @MaSP, @SoLuong, @DonGia)
END
GO

CREATE PROCEDURE CTMH_Update @MaDMH INT, @MaSP INT, @SoLuong INT, @DonGia DECIMAL(18,2)
AS
BEGIN
    UPDATE CTMH SET SoLuong=@SoLuong, DonGia=@DonGia WHERE MaDMH=@MaDMH AND MaSP=@MaSP
END
GO

CREATE PROCEDURE CTMH_Delete @MaDMH INT, @MaSP INT
AS
BEGIN
    DELETE FROM CTMH WHERE MaDMH=@MaDMH AND MaSP=@MaSP
END
GO

--11
CREATE PROCEDURE CTBH_GetAll
AS
BEGIN
    SELECT * FROM CTBH
END
GO

CREATE PROCEDURE CTBH_GetById @MaDBH INT, @MaSP INT
AS
BEGIN
    SELECT * FROM CTBH WHERE MaDBH=@MaDBH AND MaSP=@MaSP
END
GO

CREATE PROCEDURE CTBH_Insert @MaDBH INT, @MaSP INT, @SoLuong INT, @DonGia DECIMAL(18,2)
AS
BEGIN
    INSERT INTO CTBH VALUES (@MaDBH, @MaSP, @SoLuong, @DonGia)
END
GO

CREATE PROCEDURE CTBH_Update @MaDBH INT, @MaSP INT, @SoLuong INT, @DonGia DECIMAL(18,2)
AS
BEGIN
    UPDATE CTBH SET SoLuong=@SoLuong, DonGia=@DonGia WHERE MaDBH=@MaDBH AND MaSP=@MaSP
END
GO

CREATE PROCEDURE CTBH_Delete @MaDBH INT, @MaSP INT
AS
BEGIN
    DELETE FROM CTBH WHERE MaDBH=@MaDBH AND MaSP=@MaSP
END
GO

--12
--CREATE PROCEDURE SanPham_GetAll
--AS
--BEGIN
--    SELECT MaSP, TenSP, DonGia, SoLuong, AnhSP, MaLSP, MaGH
--    FROM SanPham
--    ORDER BY MaSP;
--END
--GO

CREATE PROCEDURE SanPham_GetAll
    @Search NVARCHAR(255) = NULL -- Thêm tham số @Search, có giá trị mặc định là NULL
AS
BEGIN
    SELECT MaSP, TenSP, DonGia, SoLuong, AnhSP, MaLSP, MaGH
    FROM SanPham
    WHERE @Search IS NULL 
        OR TenSP LIKE '%' + @Search + '%' -- Lọc theo TenSP nếu @Search không phải là NULL
    ORDER BY MaSP;
END
GO

CREATE PROCEDURE SanPham_GetById @MaSP INT
AS
BEGIN
    SELECT MaSP, TenSP, DonGia, SoLuong, AnhSP, MaLSP, MaGH
    FROM SanPham
    WHERE MaSP = @MaSP;
END
GO

CREATE PROCEDURE SanPham_Insert
    @TenSP NVARCHAR(100),
    @DonGia DECIMAL(18,2),
    @SoLuong INT,
	@AnhSP NVARCHAR(255),
    @MaLSP INT,
    @MaGH INT
AS
BEGIN
    DECLARE @MaSP INT = 1;
    WHILE EXISTS (SELECT 1 FROM SanPham WHERE MaSP = @MaSP)
        SET @MaSP = @MaSP + 1;

    INSERT INTO SanPham (MaSP, TenSP, DonGia, SoLuong,AnhSP, MaLSP, MaGH)
    VALUES (@MaSP, @TenSP, @DonGia, @SoLuong, @AnhSP, @MaLSP, @MaGH);
END
GO

CREATE PROCEDURE SanPham_Update
    @MaSP INT,
    @TenSP NVARCHAR(100),
    @DonGia DECIMAL(18,2),
    @SoLuong INT,
	@AnhSP NVARCHAR(255),
    @MaLSP INT,
    @MaGH INT
AS
BEGIN
    UPDATE SanPham
    SET TenSP = @TenSP,
        DonGia = @DonGia,
        SoLuong = @SoLuong,
		AnhSP = @AnhSP,
        MaLSP = @MaLSP,
        MaGH = @MaGH
    WHERE MaSP = @MaSP;
END
GO

CREATE PROCEDURE SanPham_Delete @MaSP INT
AS
BEGIN
    DELETE FROM SanPham WHERE MaSP = @MaSP;
END
GO
